name: 部署柳艺坊到GitHub Pages
on:
  push:
    branches: [ main, master ]  # 推送到主分支自动部署，仓库主分支是哪个写哪个
  workflow_dispatch:  # 支持手动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub自动生成，无需手动配置
          publish_dir: ./  # 部署根目录的所有文件（你的HTML文件就在这）
          persist-credentials: false #解决权限问题
